export const AUTH_ERROR_CODES = {
  CREDENTIALS_NOT_MATCH: "CREDENTIALS_NOT_MATCH",
  MISSING_REFRESH_TOKEN: "MISSING_REFRESH_TOKEN",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  SESSION_ERROR: "SESSION_ERROR",
  TOKEN_DELETION_FAILED: "TOKEN_DELETION_FAILED",
  MISSING_ACCESS_TOKEN: "MISSING_ACCESS_TOKEN",
  INVALID_BEARER_TOKEN: "INVALID_BEARER_TOKEN",
}

export const USER_ERROR_CODES = {
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USERNAME_ALREADY_EXISTS: "USERNAME_ALREADY_EXISTS",
}

export const TODO_ERROR_CODES = {
  TODO_NOT_FOUND: "TODO_NOT_FOUND",
  MISSING_TODO_ID: "MISSING_TODO_ID",
  TODO_DELETION_FAILED: "TODO_DELETION_FAILED",
}

export const GENERAL_ERROR_CODES = {
  INPUT_VALIDATION_FAILED: "INPUT_VALIDATION_FAILED",
}